# Generated by Django 3.1.5 on 2021-05-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.TextField(choices=[('FO', 'Food'), ('HI', 'Household Item'), ('OS', 'Office Supplies')], default='FO'),
            preserve_default=False,
        ),
    ]
