# Generated by Django 3.1.5 on 2021-06-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_auto_20210523_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='type',
            new_name='primary_type',
        ),
    ]
