# Generated by Django 3.1.5 on 2021-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_secondary_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Items/apple.jpg', upload_to='Items'),
            preserve_default=False,
        ),
    ]
