# Generated by Django 3.1.5 on 2021-07-06 19:58

from django.db import migrations, models

def forwards(apps, schema_editor):
    """
    Set the corresponding image paths of each item by using the item's name.
    """
    if schema_editor.connection.alias != 'default':
        return

    Item = apps.get_model("items", "Item")
    for item in Item.objects.all():
        item_image_name = "".join(item.name.lower().split())
        item.image = f"Items/{item_image_name}.png"
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_item_image'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]

    