# Generated by Django 3.1.5 on 2022-06-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_set_item_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='primary_type',
            new_name='primary_category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='secondary_type',
            new_name='secondary_category',
        ),
    ]
